version: "3.7"

networks:
  big-agent:
    driver: bridge

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: ba_zookeper
    networks:
      - big-agent
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:latest
    container_name: ba_kafka
    networks:
      - big-agent
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
    ports:
      - 9092:9092
      - 29092:29092

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: ba_kafdrop
    networks:
      - big-agent
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    ports:
      - 9000:9000

  consul:
    image: consul:latest
    container_name: ba_consul
    environment:
      CONSUL_BIND_INTERFACE: eth0
    ports:
      - 8500:8500
    networks:
      - big-agent
